baseURL = "https://startpage.w-ss.io/"
languageCode = "en-GB"
title = "Digital Clouds | Startpage"
theme = "bootstrap-bp-hugo-startpage"
copyright = "Salvydas Lukosius"
enableRobotsTXT = true
pygmentsCodeFences = true
canonifyurls = true
paginate = 5

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "docs"

[sitemap]
    changefreq = "weekly"
    priority = 0.5

[permalinks]
    posts = "/:year/:month/:slug/"
    post = "/:year/:month/:slug/"
    pages = "/:slug/"
    page = "/:slug/"

[Author]  
  name = "Salvydas Lukosius"

[params]
  description = "Starpage"
  #images = ["logo.jpg"]
  startPageColumns = true
  welcomeText = "Digital Clouds | Startpage"

[[params.searchEngines]]
  name = "Google"
  activated = true
  url = "https://www.google.com/search"

[[params.searchEngines]]
  name = "DuckDuckGo"
  activated = true
  url = "https://duckduckgo.com/"

[taxonomies]